#!/bin/zsh
# This hook is run after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="%{${fg[black]}%}[env: %{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg[black]}%}]%{${reset_color}%} $RPROMPT"
